# Project 1

## DS120

In [1]:
import numpy as np 
import pandas as pd

In [2]:
student = {'name':['Bill', 'Tayo', 'Jack', 'Liam', 'Sophie', 'Esther', 'Drack', 'Andrew', 'Favour', 'David'],
           'relationship':['Married', 'Divorced', 'Married', 'Single', 'Divorced', 'Single', 'Single', 'Single', 'Single', 'Single'],
           'age':[32, 45, 28, 23, 40, 24, 22, 19, 25, 27],
           'department':['Biology Education', 'Electrical Engineering', 'Computer Science', 'Law', 'Civil Engineering', 'Psychology', 'Physiology', 'Industrial Chemistry', 'Pharmacy', 'Demography']}

In [3]:
student['cgpa'] = [4.6, 3.9, 2.9, 3.0, 4.8, 3.6, 4.2, 4.5, 3.9, 4.0 ]

In [4]:
student.pop('relationship')  

['Married',
 'Divorced',
 'Married',
 'Single',
 'Divorced',
 'Single',
 'Single',
 'Single',
 'Single',
 'Single']

In [5]:
df = pd.DataFrame(student)  

In [6]:
df['admission_date'] =['2020-04-17 13:45', '2009-09-11 14:30', '2010-03-12 15:00', '2011-08-21 13:00', '2018-12-16 15:45', '2019-06-19 14:40', '2022-01-17 14:00', '2017-04-23 16:00', '2015-07-14 10:07', '2016-04-29 08:00'] #complete the code
df['gender'] = ['Male', 'Female', 'Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Male']


In [7]:
df

name  age              department  cgpa    admission_date  gender
0    Bill   32       Biology Education   4.6  2020-04-17 13:45    Male
1    Tayo   45  Electrical Engineering   3.9  2009-09-11 14:30  Female
2    Jack   28        Computer Science   2.9  2010-03-12 15:00    Male
3    Liam   23                     Law   3.0  2011-08-21 13:00    Male
4  Sophie   40       Civil Engineering   4.8  2018-12-16 15:45  Female
5  Esther   24              Psychology   3.6  2019-06-19 14:40  Female
6   Drack   22              Physiology   4.2  2022-01-17 14:00    Male
7  Andrew   19    Industrial Chemistry   4.5  2017-04-23 16:00    Male
8  Favour   25                Pharmacy   3.9  2015-07-14 10:07  Female
9   David   27              Demography   4.0  2016-04-29 08:00    Male

In [8]:
name=['Dayo', 'Cole', 'Eva', 'Bode', 'William', 'John', 'Mark', 'Paul', 'Elijah', 'Samson']
age=[32, 45, 28, 23, 40, 24, 22, 19, 25, 27]
department=['Mathematic Education', 'Chemical Engineering', 'Microbiology ', 'Insurance', 'Dramatic Art', 'sociology', 'English', 'Chemistry', 'Geology', 'Political science']
admission_date = ['2020-03-13 15:45', '1999-05-17 12:30', '2012-07-21 14:15', '2007-12-03 12:00', '2021-04-12 13:45', '2019-03-11 14:30', '2011-03-10 11:00', '2015-08-24 09:00', '2017-12-13 15:15', '2014-06-11 08:40'] 
gender = ['Male', 'Female', 'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male']
df2 = pd.DataFrame({'Name':name, 'Age':age, 'Department':department, 'Admission_date':admission_date, 'Gender':gender})
df2

Name  Age            Department    Admission_date  Gender
0     Dayo   32  Mathematic Education  2020-03-13 15:45    Male
1     Cole   45  Chemical Engineering  1999-05-17 12:30  Female
2      Eva   28         Microbiology   2012-07-21 14:15  Female
3     Bode   23             Insurance  2007-12-03 12:00    Male
4  William   40          Dramatic Art  2021-04-12 13:45    Male
5     John   24             sociology  2019-03-11 14:30    Male
6     Mark   22               English  2011-03-10 11:00    Male
7     Paul   19             Chemistry  2015-08-24 09:00    Male
8   Elijah   25               Geology  2017-12-13 15:15    Male
9   Samson   27     Political science  2014-06-11 08:40    Male

In [9]:
df['admission_date'] = pd.to_datetime (df['admission_date'])
df['year'] = df['admission_date'].dt.year
df['month'] = df['admission_date'].dt.month
df['day'] = df['admission_date'].dt.day

In [10]:
df.dtypes

name                      object
age                        int64
department                object
cgpa                     float64
admission_date    datetime64[ns]
gender                    object
year                       int64
month                      int64
day                        int64
dtype: object

In [11]:
df.isnull().sum()

name              0
age               0
department        0
cgpa              0
admission_date    0
gender            0
year              0
month             0
day               0
dtype: int64

In [12]:
df.isnull().sum()/df.shape[0]*100

name              0.0
age               0.0
department        0.0
cgpa              0.0
admission_date    0.0
gender            0.0
year              0.0
month             0.0
day               0.0
dtype: float64

In [13]:
df.name.unique()

array(['Bill', 'Tayo', 'Jack', 'Liam', 'Sophie', 'Esther', 'Drack',
       'Andrew', 'Favour', 'David'], dtype=object)

In [14]:
df.age.unique()

array([32, 45, 28, 23, 40, 24, 22, 19, 25, 27], dtype=int64)

In [15]:
df.department.unique()

array(['Biology Education', 'Electrical Engineering', 'Computer Science',
       'Law', 'Civil Engineering', 'Psychology', 'Physiology',
       'Industrial Chemistry', 'Pharmacy', 'Demography'], dtype=object)

In [16]:
df.cgpa.unique()

array([4.6, 3.9, 2.9, 3. , 4.8, 3.6, 4.2, 4.5, 4. ])

In [17]:
df.admission_date.unique()

array(['2020-04-17T13:45:00.000000000', '2009-09-11T14:30:00.000000000',
       '2010-03-12T15:00:00.000000000', '2011-08-21T13:00:00.000000000',
       '2018-12-16T15:45:00.000000000', '2019-06-19T14:40:00.000000000',
       '2022-01-17T14:00:00.000000000', '2017-04-23T16:00:00.000000000',
       '2015-07-14T10:07:00.000000000', '2016-04-29T08:00:00.000000000'],
      dtype='datetime64[ns]')

In [18]:
df.gender.unique()

array(['Male', 'Female'], dtype=object)

In [19]:
df.year.unique()

array([2020, 2009, 2010, 2011, 2018, 2019, 2022, 2017, 2015, 2016],
      dtype=int64)

In [20]:
df.month.unique()

array([ 4,  9,  3,  8, 12,  6,  1,  7], dtype=int64)

In [21]:
df.day.unique()

array([17, 11, 12, 21, 16, 19, 23, 14, 29], dtype=int64)

In [22]:
df.nunique()

name              10
age               10
department        10
cgpa               9
admission_date    10
gender             2
year              10
month              8
day                9
dtype: int64

In [23]:
df.name.value_counts()

Drack     1
Sophie    1
Jack      1
Bill      1
David     1
Tayo      1
Esther    1
Favour    1
Liam      1
Andrew    1
Name: name, dtype: int64

In [24]:
df.age.value_counts()

45    1
28    1
24    1
25    1
40    1
23    1
22    1
19    1
27    1
32    1
Name: age, dtype: int64

In [25]:
df.department.value_counts()

Physiology                1
Computer Science          1
Demography                1
Law                       1
Psychology                1
Pharmacy                  1
Electrical Engineering    1
Biology Education         1
Industrial Chemistry      1
Civil Engineering         1
Name: department, dtype: int64

In [26]:
df.admission_date.value_counts()

2017-04-23 16:00:00    1
2019-06-19 14:40:00    1
2016-04-29 08:00:00    1
2015-07-14 10:07:00    1
2011-08-21 13:00:00    1
2020-04-17 13:45:00    1
2022-01-17 14:00:00    1
2018-12-16 15:45:00    1
2010-03-12 15:00:00    1
2009-09-11 14:30:00    1
Name: admission_date, dtype: int64

In [27]:
df.gender.value_counts()

Male      6
Female    4
Name: gender, dtype: int64

In [28]:
df.year.value_counts()

2015    1
2011    1
2010    1
2009    1
2022    1
2020    1
2019    1
2018    1
2017    1
2016    1
Name: year, dtype: int64

In [29]:
df.month.value_counts()

4     3
12    1
9     1
8     1
7     1
6     1
3     1
1     1
Name: month, dtype: int64

In [30]:
df.day.value_counts()

17    2
14    1
29    1
12    1
11    1
23    1
21    1
19    1
16    1
Name: day, dtype: int64

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   name            10 non-null     object        
 1   age             10 non-null     int64         
 2   department      10 non-null     object        
 3   cgpa            10 non-null     float64       
 4   admission_date  10 non-null     datetime64[ns]
 5   gender          10 non-null     object        
 6   year            10 non-null     int64         
 7   month           10 non-null     int64         
 8   day             10 non-null     int64         
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 848.0+ bytes


In [32]:
df.describe()

age       cgpa         year      month       day
count  10.000000  10.000000    10.000000  10.000000  10.00000
mean   28.500000   3.940000  2015.700000   5.800000  17.90000
std     8.263037   0.636309     4.423423   3.259175   5.40473
min    19.000000   2.900000  2009.000000   1.000000  11.00000
25%    23.250000   3.675000  2012.000000   4.000000  14.50000
50%    26.000000   3.950000  2016.500000   5.000000  17.00000
75%    31.000000   4.425000  2018.750000   7.750000  20.50000
max    45.000000   4.800000  2022.000000  12.000000  29.00000

In [33]:
df.shape

(10, 9)

In [34]:
df[df['gender']=='Male']

name  age            department  cgpa      admission_date gender  year  \
0    Bill   32     Biology Education   4.6 2020-04-17 13:45:00   Male  2020   
2    Jack   28      Computer Science   2.9 2010-03-12 15:00:00   Male  2010   
3    Liam   23                   Law   3.0 2011-08-21 13:00:00   Male  2011   
6   Drack   22            Physiology   4.2 2022-01-17 14:00:00   Male  2022   
7  Andrew   19  Industrial Chemistry   4.5 2017-04-23 16:00:00   Male  2017   
9   David   27            Demography   4.0 2016-04-29 08:00:00   Male  2016   

   month  day  
0      4   17  
2      3   12  
3      8   21  
6      1   17  
7      4   23  
9      4   29

In [35]:
df['cgpa'].mean()

3.94

In [36]:
df['cgpa'].max()

4.8

In [37]:
df['cgpa'].min()

2.9

In [38]:
df['cgpa'].sum()

39.4

In [39]:
df

name  age              department  cgpa      admission_date  gender  \
0    Bill   32       Biology Education   4.6 2020-04-17 13:45:00    Male   
1    Tayo   45  Electrical Engineering   3.9 2009-09-11 14:30:00  Female   
2    Jack   28        Computer Science   2.9 2010-03-12 15:00:00    Male   
3    Liam   23                     Law   3.0 2011-08-21 13:00:00    Male   
4  Sophie   40       Civil Engineering   4.8 2018-12-16 15:45:00  Female   
5  Esther   24              Psychology   3.6 2019-06-19 14:40:00  Female   
6   Drack   22              Physiology   4.2 2022-01-17 14:00:00    Male   
7  Andrew   19    Industrial Chemistry   4.5 2017-04-23 16:00:00    Male   
8  Favour   25                Pharmacy   3.9 2015-07-14 10:07:00  Female   
9   David   27              Demography   4.0 2016-04-29 08:00:00    Male   

   year  month  day  
0  2020      4   17  
1  2009      9   11  
2  2010      3   12  
3  2011      8   21  
4  2018     12   16  
5  2019      6   19  
6  2022      1   17  
7  2017      4   23  
8  2015      7   14  
9  2016      4   29

In [40]:
df.to_csv('df.csv', index=False)